version: '3.3'

services:
  db:
    build: ./db
    # volumes:
    #   - './db/start_up.sql:/docker-entrypoint-initdb.d/'
    ports:
      - '5432:5432'

  api:
    build: .
    volumes:
      - './requirements.txt:/app'
    network_mode: 'host'
    depends_on:
      - db
