version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:3000"
    volumes:
      - ./app:/app
    depends_on:
      - db  
    platform: linux/amd64  # Specify the default platform here if needed

  db:
    image: "postgres:latest"
    container_name: my_postgres_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
      
volumes:
 postgres_data:
