version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api
    ports:
      - "80:80"
    depends_on:
      - mysql
    networks:
      - movie-network

  mysql:
    image: mysql:latest
    container_name: movie-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: movie
      MYSQL_PASSWORD: ""
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./createDb.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - movie-network

networks:
  movie-network:  
    driver: bridge
  
volumes:
  mysql_data:
