version: "3"
services:
    movieservice:
        build: .
        container_name: moviedb
        ports:
            - "5000:5000"
        volumes:
            - "./:/DockerMovieDB"
        command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
