version: "3.11.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "123456"
