[tool.poetry]
name = "backend"
version = "0.1.0"
description = "Teste de backend para Inowatt"
authors = ["João Maranhão"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
