# Generated by Django 4.1.1 on 2022-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("MovieId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("yearRelease", models.CharField(max_length=4)),
                ("genre", models.CharField(max_length=50)),
                ("budgetCost", models.IntegerField()),
                ("countryOrigin", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=1000)),
            ],
        ),
    ]
